---
- name: Download and install packages
  apt:
    name: '{{ packages }}'
  vars:
    packages:
      - neovim
      - python3
      - python3-pip
      - chromium-browser
      - curl
      - wget
      - git
